region: ap-northeast-1
cluster: example-prod-ebisawa
service: example-prod-ebisawa
service_definition: ecs-service-def.json
task_definition: ecs-task-def.json
timeout: 10m0s

plugins:
  - name: tfstate
    config:
      url: s3://gachimuchi-tfstate/example/prod/cicd/app_ebisawa_v1.0.0.tfstate
